### ISSUE TITLE
malice on linux can't find the configs

### ISSUE THREAD

**Issue by blacktop** [maliceio/malice#26]
```bash
vagrant@vagrant-ubuntu-trusty-64:~$ malice -D lookup 6fe80e56ad4de610304bab1675ce84d16ab6988e
ERRO[0000] "open /home/vagrant/.malice/config.toml: no such file or directory"
goroutine 1 [running, locked to thread]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0xf66780, 0xc4202a58c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x23)
	/home/vagrant/go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x90
github.com/maliceio/malice/malice/errors.CheckError(0xf66780, 0xc4202a58c0, 0xc42028b800)
	/home/vagrant/go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x62
github.com/maliceio/malice/config.Load()
	/home/vagrant/go/src/github.com/maliceio/malice/config/load.go:120 +0x342
github.com/maliceio/malice/malice/logger.Init()
	/home/vagrant/go/src/github.com/maliceio/malice/malice/logger/logger.go:55 +0x26
main.init.1()
	/home/vagrant/go/src/github.com/maliceio/malice/main.go:20 +0x14
main.init()
	/home/vagrant/go/src/github.com/maliceio/malice/main.go:82 +0x65
```

**Comment by blacktop** [comment]
works now
