### ISSUE TITLE
Invalid memory address

### ISSUE THREAD

**Issue by agucova** [maliceio/malice#35]
**Output of `go version`:**

```
go version go1.7.1 darwin/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:32:50 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: LIAJ:H4I2:Y56S:4YLO:U3DD:A2NW:U6JB:GBH7:TS3H:OVEH:EDOV:A37W
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 33
 System Time: 2016-10-14T23:00:00.642758435Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

I'm using Docker Toolbox.

**Steps to reproduce the issue:**
`$ ~ λ malice --debug scan /Users/ForgottenPlayer/Downloads/pprx.exe `

**Describe the results you received:**
I got an error stating:
```
DEBU[0000] Malice config loaded from /Users/ForgottenPlayer/.malice/config.toml 
DEBU[0000] Malice plugins loaded from /Users/ForgottenPlayer/.malice/plugins.toml 
DEBU[0000] Malice Version: 0.1.0-alpha, build HEAD      
DEBU[0000] Trusting 1 certs                             
DEBU[0000] Connected to docker daemon with docker-machine  ip=192.168.99.100 port=2376
DEBU[0000] Searching for container: rethink              env=development
DEBU[0000] name:  rethink   container.Name:  rethink    
DEBU[0000] MATCH:  true                                 
DEBU[0000] Container FOUND: rethink                      env=development
DEBU[0000] Attempting to connect to: rethink:28015      
DEBU[0000] Attempting to connect to: 172.17.0.2:28015   
DEBU[0002] Attempting to connect to: localhost:28015    
ERRO[0002] "runtime error: invalid memory address or nil pointer dereference"
goroutine 1 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0x48ba940, 0xc420016080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x45bb740)
	/private/tmp/malice-20160913-13247-1qvpfbq/gopath/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x90
github.com/maliceio/malice/malice/errors.CheckError(0x48ba940, 0xc420016080, 0x4)
	/private/tmp/malice-20160913-13247-1qvpfbq/gopath/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x62
main.main()
	/private/tmp/malice-20160913-13247-1qvpfbq/gopath/src/github.com/maliceio/malice/main.go:80 +0x36e
```

**Comment by blacktop** [comment]
How did you install **malice**?

**Comment by agucova** [comment]
Ok, I reinstalled everything, go, docker for mac and malice (according to the documentation).
The initial error disappeared, but now this happens.
```
~ λ malice scan /Users/ForgottenPlayer/Downloads/pprx.exe 
ERRO[0000] ELK is NOT running, starting now...          
~ λ malice scan /Users/ForgottenPlayer/Downloads/pprx.exe 
ERRO[0000] ELK is NOT running, starting now...          
ERRO[0000] StartContainer error = Error response from daemon: driver failed programming external connectivity on endpoint awesome_sinoussi (0d42841e413f500e88588f368f3a49a925781422a49e3f1dda62fd5409d9a472): Bind for 0.0.0.0:9200 failed: port is already allocated
  env=development
```
It exits the first time, and the second time it tries to start elk again, failing as the port is already used.
A debug log: https://gist.github.com/agucova/18e21111113b01121278773fef68cdbf

**Comment by blacktop** [comment]
can you do a `docker rm -f pedantic_turing` and then try again?

**Comment by agucova** [comment]
It didn't work, so I had a hunch a reinstalled everything again, but installing docker from homebrew. I tried everything again, and it's installing the plugins!
I will update if any errors appears further, but it seems to be working.

**Comment by blacktop** [comment]
Did that end up working for you?

I was just able to recreate the behavior you were seeing.  This was due to having an old installs config files left over in your `$HOME/.malice folder`.  I will add some documentation/fixes to remove those with a `brew remove` etc.  Thank you
