### ISSUE TITLE
Docker in Docker install - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eucalyptus30** [maliceio/malice#51]
**Output of `go version`:**

```
go version go1.8.1 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 75
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 165
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.784GiB
Name: pcfixe
ID: Z5OE:S2LE:MED4:CDUX:SXGX:STDV:AVKM:PBKN:UQSD:G6NG:GPWS:ELM5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**
```
Operating System: Debian GNU/Linux 8.8 (jessie)
Kernel: Linux 3.16.0-4-amd64
Architecture: x86-64
Memory: 8GB
```

**Steps to reproduce the issue:**
1. docker run --rm -v /var/run/docker.sock:/var/run/docker.sock malice/engine plugin update --all

**Describe the results you received:**
I've this error
```
[Updating Plugin] ===>  javascript
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55bdc25c6779]

goroutine 1 [running]:
panic(0x55bdc2cab980, 0xc420012050)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/maliceio/malice/malice/docker/client/image.Pull(0xc420384ab0, 0xc42034c980, 0x11, 0x55bdc2920fc6, 0x6)
	/go/src/github.com/maliceio/malice/malice/docker/client/image/image.go:40 +0xf9
github.com/maliceio/malice/plugins.UpdateAllPlugins(0xc420384ab0)
	/go/src/github.com/maliceio/malice/plugins/plugins.go:261 +0x306
github.com/maliceio/malice/commands.cmdUpdatePlugin(0x0, 0x0, 0x1, 0x0, 0xc4203660c0)
	/go/src/github.com/maliceio/malice/commands/plugin.go:161 +0x277
github.com/maliceio/malice/commands.glob..func8(0xc4202d3a40, 0x0, 0xc4202d3a40)
	/go/src/github.com/maliceio/malice/commands/commands.go:138 +0xc5
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x55bdc2c82660, 0x55bdc2d65e20, 0xc4202d3a40, 0xc420366000, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd6
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x55bdc29211a0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bdc29258f2, 0xd, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb98
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420091860, 0xc4202d37c0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:374 +0xb1c
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.startApp(0x55bdc292104a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bdc2930cca, 0x1f, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:294 +0x82e
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x55bdc292104a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bdc2930cca, 0x1f, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:93 +0x16a7
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc4200916c0, 0xc42000c180, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x814
main.main()
	/go/src/github.com/maliceio/malice/main.go:88 +0x54a
```

<details>
  <summary>Click here if you want to see the full result of the command</summary>
  <p>

  ```
nicolas@pcfixe: ~ # docker run --rm -v /var/run/docker.sock:/var/run/docker.sock malice/engine plugin update --all
latest: Pulling from library/busybox
Digest: sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f
Status: Image is up to date for busybox:latest
5.3: Pulling from blacktop/elasticsearch
Digest: sha256:081d4717e9d570a39f33f6cbed23879d507b361a6a22b6463fc90a7a31be9eb6
Status: Image is up to date for blacktop/elasticsearch:5.3
[Updating Plugin] ===>  nsrl
sha1: Pulling from malice/nsrl
Digest: sha256:c7e50532b1861841b4a78af375abc617c07e93400bf87b303978e86f21a38edc
Status: Image is up to date for malice/nsrl:sha1
[Updating Plugin] ===>  virustotal
latest: Pulling from malice/virustotal
Digest: sha256:99d4a908677c86d9a5d576edf2b1309038f10eb221caf6fb432324f8d7d3c9fe
Status: Image is up to date for malice/virustotal:latest
[Updating Plugin] ===>  totalhash
latest: Pulling from malice/totalhash
Digest: sha256:42a49d9628919089e9093a1de54767371206abc56fe3a7f2754f89371e2cedb4
Status: Image is up to date for malice/totalhash:latest
[Updating Plugin] ===>  shadow-server
latest: Pulling from malice/shadow-server
Digest: sha256:729ee2dee5912fbba9c5df0324294855df8e11b7d0cc1da30ea45265764c1615
Status: Image is up to date for malice/shadow-server:latest
[Updating Plugin] ===>  team-cymru
latest: Pulling from malice/team-cymru
3c3d46b04bf5: Already exists 
a3ed95caeb02: Already exists 
eb1c9d68a781: Already exists 
043ca925c043: Already exists 
Digest: sha256:99c1d8b92d47cf720c1b6bfd0a9123eab8086d1b0896d8f1e465fed2ed652880
Status: Image is up to date for malice/team-cymru:latest
[Updating Plugin] ===>  fileinfo
latest: Pulling from malice/fileinfo
Digest: sha256:7bee3f79b38c97f2bcd60457d3e2daf6aeb1205c465089ea732787ac46e1103e
Status: Image is up to date for malice/fileinfo:latest
[Updating Plugin] ===>  yara
latest: Pulling from malice/yara
Digest: sha256:d9e2173cf99b23f514007a2300a1833beda1af9c52d9eac6808e04f48ca133ca
Status: Image is up to date for malice/yara:latest
[Updating Plugin] ===>  avast
latest: Pulling from malice/avast
Digest: sha256:834aa8ac01927d446345e2e0ed85437ad7e3ade40060a62583f388e0ae87b71b
Status: Image is up to date for malice/avast:latest
[Updating Plugin] ===>  avg
latest: Pulling from malice/avg
Digest: sha256:211130df8460da113c3cef33ead4b6c3a448a1e5d07d0f01948540c3f1e93d3b
Status: Image is up to date for malice/avg:latest
[Updating Plugin] ===>  bitdefender
latest: Pulling from malice/bitdefender
Digest: sha256:bf74082342d7299cfa4cf7a26873041da23f3da66b2859b42d5b95476d846e30
Status: Image is up to date for malice/bitdefender:latest
[Updating Plugin] ===>  clamav
latest: Pulling from malice/clamav
Digest: sha256:d04bcc8533b3d5ede065820592eb023137dde13218e3159e6de8cef7dcc2260f
Status: Image is up to date for malice/clamav:latest
[Updating Plugin] ===>  comodo
latest: Pulling from malice/comodo
Digest: sha256:38ab2b80022a52c5015376af39131b34e248001d7f70ba96ad1b18d4a47718ad
Status: Image is up to date for malice/comodo:latest
[Updating Plugin] ===>  fprot
latest: Pulling from malice/fprot
Digest: sha256:77b9048dea806d06914369cef04544e0238154de3032a5d474fa09c13bd2410a
Status: Image is up to date for malice/fprot:latest
[Updating Plugin] ===>  fsecure
latest: Pulling from malice/fsecure
Digest: sha256:5f8ef723b5c65b66c9b54197df4b5ebde99d375a8b4fdbc14f8c5d10e7634eac
Status: Image is up to date for malice/fsecure:latest
[Updating Plugin] ===>  sophos
latest: Pulling from malice/sophos
Digest: sha256:7f7ea8d7a2e46e80a66c9127b49fd682d603f748bad8dfe08e7f4aa1cb037f3d
Status: Image is up to date for malice/sophos:latest
[Updating Plugin] ===>  pe
latest: Pulling from malice/pe
Digest: sha256:372193ef5659e5e5255ca0a2300ecfb1e56ae8add0197e5bfe4acf7889537fec
Status: Image is up to date for malice/pe:latest
[Updating Plugin] ===>  floss
latest: Pulling from malice/floss
Digest: sha256:e4cd9a502f7735db1893e548ed04893404a2a2579912e9a7055669eb94c2c406
Status: Image is up to date for malice/floss:latest
[Updating Plugin] ===>  office
latest: Pulling from malice/office
Digest: sha256:800644b60d231dda4cc4b11671145c37c1215bb7567f064e072a7a8b25d53d5f
Status: Image is up to date for malice/office:latest
[Updating Plugin] ===>  pdf
latest: Pulling from malice/pdf
Digest: sha256:9d87327d8214efa6c5a392a1d5b6bca282c676e094d77d4e3aa17b6f46da4b92
Status: Image is up to date for malice/pdf:latest
[Updating Plugin] ===>  javascript
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55bdc25c6779]

goroutine 1 [running]:
panic(0x55bdc2cab980, 0xc420012050)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/maliceio/malice/malice/docker/client/image.Pull(0xc420384ab0, 0xc42034c980, 0x11, 0x55bdc2920fc6, 0x6)
	/go/src/github.com/maliceio/malice/malice/docker/client/image/image.go:40 +0xf9
github.com/maliceio/malice/plugins.UpdateAllPlugins(0xc420384ab0)
	/go/src/github.com/maliceio/malice/plugins/plugins.go:261 +0x306
github.com/maliceio/malice/commands.cmdUpdatePlugin(0x0, 0x0, 0x1, 0x0, 0xc4203660c0)
	/go/src/github.com/maliceio/malice/commands/plugin.go:161 +0x277
github.com/maliceio/malice/commands.glob..func8(0xc4202d3a40, 0x0, 0xc4202d3a40)
	/go/src/github.com/maliceio/malice/commands/commands.go:138 +0xc5
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x55bdc2c82660, 0x55bdc2d65e20, 0xc4202d3a40, 0xc420366000, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd6
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x55bdc29211a0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bdc29258f2, 0xd, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb98
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420091860, 0xc4202d37c0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:374 +0xb1c
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.startApp(0x55bdc292104a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bdc2930cca, 0x1f, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:294 +0x82e
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x55bdc292104a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bdc2930cca, 0x1f, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:93 +0x16a7
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc4200916c0, 0xc42000c180, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x814
main.main()
	/go/src/github.com/maliceio/malice/main.go:88 +0x54a
 ```
 </p></details>

<br />

**Describe the results you expected:**
Install of all Plugins

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker ps -a`:**

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                      NAMES
f06896879f4a        nberna/nginx        "/start.sh"              18 months ago       Up 22 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
7d04af9aa555        nberna/php          "/start.sh"              18 months ago       Up 22 minutes       9000/tcp                                   php
f04d8e7adabb        mariadb             "/docker-entrypoin..."   18 months ago       Up 22 minutes       3306/tcp                                   bdd
```
no container created.

Any idea why the install of Docker in Docker doesn't work on my computer ?

Thanks a lot,
Euca

**Comment by blacktop** [comment]
@eucalyptus30 that is just the install of the `malice/javascript` plugin failing.  It should still be able to scan though?  I will make a new release that disables that plugin in the `~/.malice/comfig/config.toml` (you can also fix it by going in there and disabling that plugin) so it won't try and download it as it (the plugin) is not done and is still a WIP.  Thank you for letting me know about this and if this still doesn't work be sure to re-open this issue.

**Comment by blacktop** [comment]
So that is a mistake in the docs can you try to do this instead:

```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock malice/engine plugin update
```

**Comment by blacktop** [comment]
Ok so I apologize for the the confusion.  I believe I understand the issue now, however, I can't build it as **docker** moving to **moby** has broken a lot of things in malice so it is not properly building new docker containers.  I will begin the process of moving to **moby** soon, but in the mean time you can skip that first doc instruction and just do a `scan` as the scan will also install the plugins if they don't exist the first time you run malice and it should not try to install `disabled` plugins.  `malice/javascript` is disabled now as it is not ready yet.  Thank you for bringing this to my attention and thank you for trying malice 😄

**Comment by vmorgo** [comment]
Hi, "blacktop":

Any movement on the conversion to Moby?  Still experiencing issues similar to the above.  I tried to log a bug earlier today (much the same as this one--basically, constant prompts to install newer version 0.3.2, constant over-writes of ~/.malice/config/config.toml with outdated information and never-ending complaints about the docker containter(s); and elasticsearch:5.3 still being pulled when Kibana wants 5.4 or better and kibana (elk) doesn't work at all...  

Using Ubuntu 16.04.03 in a KVM virtual machine.  Scanning and watching functions do seem to work, though they are very slow.

Please advise soonest--I figure no point in resubmitting what is essentially the same bug.

**Comment by blacktop** [comment]
the "movement" is happening in the `maliceio/engine` repo
