### ISSUE TITLE
dial tcp  lookup ElasticSearch no such host

### ISSUE THREAD

**Issue by dsslimshaddy** [maliceio/malice#57]
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
                -v `pwd`:/malice/samples \
                -e MALICE_VT_API=$MALICE_VT_API \
                malice/engine -D scan SAMPLE
```

gives me this error

```
DEBU[0000] Malice config loaded from: /malice/config/config.toml 
DEBU[0000] config.toml version: v0.3.2, malice version: dev 
DEBU[0000] Malice plugins loaded from plugins/bindata.go 
DEBU[0000] Using 2 PROCS                                
DEBU[0000] Malice Version: dev, commit none, built at unknown 
DEBU[0000] Running inside Docker...                     
DEBU[0000] Connected to docker daemon client             ip=localhost port=2375
DEBU[0000] Searching for container: malice-elastic       env=development
DEBU[0000] name:  malice-elastic   container.Name:  eloquent_cray 
DEBU[0000] MATCH:  false                                
DEBU[0000] name:  malice-elastic   container.Name:  shadow-server 
DEBU[0000] MATCH:  false                                
DEBU[0000] name:  malice-elastic   container.Name:  malice-elastic 
DEBU[0000] MATCH:  true                                 
DEBU[0000] Container FOUND: malice-elastic               env=development
DEBU[0000] Elasticsearch is running.                     image="blacktop/elasticsearch:5.3" ip= network=default
DEBU[0000] Attempting to PING to: http://elasticsearch:9200 

ERRO[0000] "Get http://elasticsearch:9200/: dial tcp: lookup elasticsearch on 67.207.67.2:53: no such host"
goroutine 1 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0x563a27fd48c0, 0xc4203e8420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x92
github.com/maliceio/malice/malice/errors.CheckError(0x563a27fd48c0, 0xc4203e8420, 0xc42017cd00)
        /go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x64
github.com/maliceio/malice/malice/database/elasticsearch.InitElasticSearch(0x0, 0x0, 0x1, 0x1)
        /go/src/github.com/maliceio/malice/malice/database/elasticsearch/elasticsearch.go:124 +0x6a
github.com/maliceio/malice/commands.ScanSample(0x7fffc1f4ef41, 0x6)
        /go/src/github.com/maliceio/malice/commands/scan.go:58 +0x45e
github.com/maliceio/malice/commands.cmdScan(0x7fffc1f4ef41, 0x6, 0x0, 0xc42032c000, 0x0)
        /go/src/github.com/maliceio/malice/commands/scan.go:22 +0x37
github.com/maliceio/malice/commands.glob..func1(0xc4202d5900, 0x0, 0xc4202d5900)
        /go/src/github.com/maliceio/malice/commands/commands.go:25 +0x8c
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x563a27c18660, 0x563a27cfbde8, 0xc4202d5900, 0xc42032c000, 0x0)
        /go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd6
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x563a278b613b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x563a278b9eea, 0xb, 0x0, ...)
        /go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb98
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc42007bba0, 0xc42000c0f0, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x814
main.main()
        /go/src/github.com/maliceio/malice/main.go:88 +0x54a

 
2017/09/04 18:55:52 Head http://elasticsearch:9200/malice: dial tcp: lookup elasticsearch on 67.207.67.2:53: no such host
```

im using ubuntu 16.04 on vps.

`malice scan SAMPLE` is also giving the same error but with 
  - `http://localhost:9200/malice` instead of `http://elasticsearch:9200/malice`  
  - `connection refused` instead of `no such host`

Its strange why hostname would be elasticsearch

it worked a few times but suddenly its not working anymore 

P.S also getting 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x564fd50ac779]
...
```

when running the update 
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock malice/engine plugin update --all`

## UPDATE 

So i did `docker-clean stop` then ran `malice scan SAMPLE` . it ran fine then again same problem. so after every time i have to do `docker-clean stop` why is that ?

**Comment by blacktop** [comment]
so I changed malice's config to use `malice/elasticsearch` instead of `blacktop/elasticseach:5.3`  it is weird that it is still trying to use the old one.  

can look in your `~/.malice/config/config.toml` and tell me what it wants to use for the DB etc?

**Comment by blacktop** [comment]
also the `docker` version of `malice` is the old version as I wasn't able to update it as well as the pre-complied binary because of the way docker renamed itself to `moby` it broke all the dependancies (something that is fixed in the new re-writen version)

**Comment by blacktop** [comment]
can you tell me what host/port elasticsearch is on?

`docker ps -a`

**Comment by dsslimshaddy** [comment]
malice (non docker pre-compiled) is running  malice/elasticsearch:5.5 ( the above output is from docker version )
this below is from pre compiled one (`malice -D scan SAMPLE `)
```
root@virustotal:~# malice -D scan SAMPLE
DEBU[0000] Malice config loaded from: /root/.malice/config/config.toml 
DEBU[0000] config.toml version: v0.3.11, malice version: 0.3.11 
DEBU[0000] Malice plugins loaded from: /root/.malice/plugins/plugins.toml 
DEBU[0000] Using 2 PROCS                                
DEBU[0000] Malice Version: 0.3.11, commit 9e7f91e08345f227b4ddfe3690bc5ee52d1c6feb, built at 2017-07-22T23:52:36Z 
DEBU[0000] Running inside Docker...                     
DEBU[0000] Connected to docker daemon client             ip=localhost port=2375
DEBU[0000] Searching for container: malice-elastic       env=development
DEBU[0000] name:  malice-elastic   container.Name:  malice-elastic 
DEBU[0000] MATCH:  true                                 
DEBU[0000] Container FOUND: malice-elastic               env=development
DEBU[0000] Elasticsearch is running.                     image="malice/elasticsearch:5.5" ip= network=default
DEBU[0000] Attempting to PING to: http://localhost:9200 
ERRO[0000] "Get http://localhost:9200/: dial tcp 127.0.0.1:9200: getsockopt: connection refused"
```

here is `~/malice/config/config.toml`
```
[database]
  name = "malice-elastic"
  image = "malice/elasticsearch:5.5"
  server = "127.0.0.1"
  ports = [9200]
  timeout = 20
  enabled = true

[ui]
  name = "malice-kibana"
  image = "malice/kibana:5.5"
  server = "127.0.0.1"
  ports = [443]
  enabled = true

[environment]
  run = "development"

[docker]
  machine-name = "malice"
  endpoint = "tcp://localhost:2376"
  timeout = 120
  binds = "malice:/malware:ro"
  links = "malice-elastic:elasticsearch"
  cpu = 500000000
```

`docker ps -a` shows this

```

CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                       PORTS               NAMES
4dbf90bedc99        malice/elasticsearch   "/elastic-entrypoi..."   2 minutes ago       Exited (137) 2 minutes ago                       malice-elastic
```

**Comment by blacktop** [comment]
aw ok so elasticsearch is exiting  

can you run

`docker logs malice-elastic`

**Comment by dsslimshaddy** [comment]
```
[2017-09-04T21:27:13,124][INFO ][o.e.n.Node               ] [] initializing ...
[2017-09-04T21:27:13,187][INFO ][o.e.e.NodeEnvironment    ] [QlovV87] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda1)]], net usable_space [8.3gb], net total_space [19.2gb], spins? [possibly], types [ext4]
[2017-09-04T21:27:13,188][INFO ][o.e.e.NodeEnvironment    ] [QlovV87] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-09-04T21:27:13,189][INFO ][o.e.n.Node               ] node name [QlovV87] derived from node ID [QlovV87_T-6tAJYzRoA3Iw]; set [node.name] to override
[2017-09-04T21:27:13,189][INFO ][o.e.n.Node               ] version[5.5.2], pid[1], build[b2f0c09/2017-08-14T12:33:14.154Z], OS[Linux/4.4.0-87-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-09-04T21:27:13,189][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [aggs-matrix-stats]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [ingest-common]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [lang-expression]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [lang-groovy]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [lang-mustache]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [lang-painless]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [parent-join]
[2017-09-04T21:27:13,922][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [percolator]
[2017-09-04T21:27:13,923][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [reindex]
[2017-09-04T21:27:13,923][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [transport-netty3]
[2017-09-04T21:27:13,923][INFO ][o.e.p.PluginsService     ] [QlovV87] loaded module [transport-netty4]
[2017-09-04T21:27:13,923][INFO ][o.e.p.PluginsService     ] [QlovV87] no plugins loaded
[2017-09-04T21:27:15,506][INFO ][o.e.d.DiscoveryModule    ] [QlovV87] using discovery type [zen]
[2017-09-04T21:27:16,084][INFO ][o.e.n.Node               ] initialized
[2017-09-04T21:27:16,084][INFO ][o.e.n.Node               ] [QlovV87] starting ...
[2017-09-04T21:27:16,224][INFO ][o.e.t.TransportService   ] [QlovV87] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2017-09-04T21:27:16,235][INFO ][o.e.b.BootstrapChecks    ] [QlovV87] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-09-04T21:27:19,308][INFO ][o.e.c.s.ClusterService   ] [QlovV87] new_master {QlovV87}{QlovV87_T-6tAJYzRoA3Iw}{a9mcr4aGRkaK7qqEzmF-Sw}{172.17.0.2}{172.17.0.2:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-09-04T21:27:19,346][INFO ][o.e.h.n.Netty4HttpServerTransport] [QlovV87] publish_address {172.17.0.2:9200}, bound_addresses {0.0.0.0:9200}
[2017-09-04T21:27:19,346][INFO ][o.e.n.Node               ] [QlovV87] started
[2017-09-04T21:27:19,358][INFO ][o.e.g.GatewayService     ] [QlovV87] recovered [0] indices into cluster_state
[2017-09-04T21:27:20,195][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
[2017-09-04T21:27:20,324][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [sha1]
[2017-09-04T21:27:20,326][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [path]
[2017-09-04T21:27:20,327][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [sha256]
[2017-09-04T21:27:20,328][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [size]
[2017-09-04T21:27:20,329][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [mime]
[2017-09-04T21:27:20,330][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [name]
[2017-09-04T21:27:20,330][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [sha512]
[2017-09-04T21:27:20,330][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [md5]
[2017-09-04T21:27:20,355][INFO ][o.e.c.m.MetaDataCreateIndexService] [QlovV87] [malice] creating index, cause [api], templates [], shards [1]/[0], mappings [_default_, samples]
[2017-09-04T21:27:20,540][INFO ][o.e.c.r.a.AllocationService] [QlovV87] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[malice][0]] ...]).
[2017-09-04T21:27:22,979][INFO ][o.e.c.m.MetaDataMappingService] [QlovV87] [malice/-ieUW2hxQrOK15YiUOOdDA] update_mapping [samples]
[2017-09-04T21:27:23,816][INFO ][o.e.c.m.MetaDataMappingService] [QlovV87] [malice/-ieUW2hxQrOK15YiUOOdDA] update_mapping [samples]
[2017-09-04T21:27:25,528][INFO ][o.e.c.m.MetaDataMappingService] [QlovV87] [malice/-ieUW2hxQrOK15YiUOOdDA] update_mapping [samples]
```

**Comment by blacktop** [comment]
is there more logs?  that looks like it started properly I don't understand why it exited?

**Comment by blacktop** [comment]
can I ask how much RAM that VPS has?

**Comment by dsslimshaddy** [comment]
VPS has 3 gb of ram. and i also did that elastic search fix mentioned .

no more logs it ends there

**Comment by dsslimshaddy** [comment]
So i removed everything did a clean install.

ran `malice scan  -D SAMPLE` asks to install plugins. runs scans fine.

i did 

`$ ifconfig docker0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
gave me   `"172.17.0.2"`

i changed 

```
[database]
  server = "localhost"
```
to 
```
[database]
  server = "172.17.0.2"
```
then again did `malice scan SAMPLE`

got the error same as above
```
DEBU[0000] Elasticsearch is running.                     image="malice/elasticsearch" ip= network=default
DEBU[0000] Attempting to PING to: http://localhost:9200 
ERRO[0000] "Get http://localhost:9200/: dial tcp 127.0.0.1:9200: getsockopt: connection refused"
```
what i dont get is why its dialing to 127.0.0.1 when i changed it to 172.17.0.2 ?

**Comment by dsslimshaddy** [comment]
also to add  i havent installed or started elasticsearch externally . i hope the docker images from malice installation does that for me.

**Comment by dsslimshaddy** [comment]
hmm looks like elasticsearch is exiting after 1st scan.

**Comment by blacktop** [comment]
that is very strange.  I wonder if it is an artifact of it running on a VPS?

**Comment by blacktop** [comment]
maybe if you manually started elasticsearch like this:

```bash
$ docker run -d --name malice-elastic -p 9200:9200 -e ES_JAVA_OPTS="-Xms2g -Xmx2g" malice/elasticsearch
```

That will tell it to use 2GB instead of the 4GB I think it wants by default.

**Comment by dsslimshaddy** [comment]
We missed a small part is that  `Exited (137)` therefore elasticsearch is out of memory.
i upgraded to 8gb ram server and it ran without any problems.

haven't tried with 4gb ill update if i try.
