### ISSUE TITLE
issue when update pe

### ISSUE THREAD

**Issue by ikcla** [maliceio/malice#59]
**Output of `go version`:**

```
[
```

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
Updating Plugin] ===>  pe
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8675c5b779]

goroutine 1 [running]:
panic(0x8676340980, 0xc420012050)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/maliceio/malice/malice/docker/client/image.Pull(0xc4203b4ae0, 0xc42037c5c0, 0x9, 0x8675fb5fc6, 0x6)
	/go/src/github.com/maliceio/malice/malice/docker/client/image/image.go:40 +0xf9
github.com/maliceio/malice/plugins.UpdateAllPlugins(0xc4203b4ae0)
	/go/src/github.com/maliceio/malice/plugins/plugins.go:261 +0x306
github.com/maliceio/malice/commands.cmdUpdatePlugin(0x0, 0x0, 0x1, 0x0, 0xc42039e060)
	/go/src/github.com/maliceio/malice/commands/plugin.go:161 +0x277
github.com/maliceio/malice/commands.glob..func8(0xc420311a40, 0x0, 0xc420311a40)
	/go/src/github.com/maliceio/malice/commands/commands.go:138 +0xc5
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x8676317660, 0x86763fae20, 0xc420311a40, 0xc42039e000, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd6
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x8675fb61a0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8675fba8f2, 0xd, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb98
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc42032c680, 0xc4203117c0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:374 +0xb1c
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.startApp(0x8675fb604a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8675fc5cca, 0x1f, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:294 +0x82e
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x8675fb604a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8675fc5cca, 0x1f, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:93 +0x16a7
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc42032c4e0, 0xc42008e100, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x814
main.main()
	/go/src/github.com/maliceio/malice/main.go:88 +0x54a
```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**

**Steps to reproduce the issue:**
1. docker run --rm -v /var/run/docker.sock:/var/run/docker.sock malice/engine plugin update --all
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ikcla** [comment]
broke initial run docker

**Comment by blacktop** [comment]
So I think this is just an issue with the Docker IN Docker version of malice.  When docker changed it's name to moby it broke the docker install because it messed up all the dependancies.  

I apologize and and working on a fix with a re-write here: [maliceio/engine](https://github.com/maliceio/engine), but it is not ready yet. 😞

**Comment by blacktop** [comment]
Can you try one of the binary releases? https://github.com/maliceio/malice/releases

**Comment by blacktop** [comment]
Is this still an issue with the latest release? https://github.com/maliceio/malice/releases/tag/v0.3.26

This issue has been automatically marked as stale because it has not had
recent activity. It will be closed if no further activity occurs. Thank you
for your contributions.
