### ISSUE TITLE
plugins.av.clamav field not present in the report

### ISSUE THREAD

**Issue by pielco11** [maliceio/malice#62]
**Output of `go version`:**

```
go version go1.8.3 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 313
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 411
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-19-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.746 GiB
Name: notebook
ID: ZFKE:ULQR:BKKX:3TH7:TV6Z:NDAX:52YB:OMXP:BOWS:UUKT:FM2R:UNAE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: pielco11
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**

Physical, ubuntu 17.10

**Steps to reproduce the issue:**
1. Scan a file with `./malice scan /path/to/malware.exe`
2. Don't see the field `plugins.av.clamav` in the report
3. Run `./malice -D scan /path/to/malware.exe`

**Describe the results you received:**
```
DEBU[0011] Searching for container: clamav               env=development
DEBU[0011] name:  clamav   container.Name:  clamav      
DEBU[0011] MATCH:  true                                 
DEBU[0011] Container FOUND: clamav                       env=development
ERRO[0011] Container is already running...               env=development exisits=true name=clamav
DEBU[0011] Plugin Container Started                      env=development name=
ERRO[0011] "container is already running"
goroutine 57 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0xdef020, 0xc420378b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201ba9c0)
	/Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x7d
github.com/maliceio/malice/malice/errors.CheckError(0xdef020, 0xc420378b80, 0xc420387170)
	/Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x62
github.com/maliceio/malice/plugins.Plugin.StartPlugin(0xc42032fcb0, 0x6, 0x1, 0xc42032fe00, 0x2, 0xc42032fd70, 0x6, 0xc42032feb0, 0xd, 0xc420314e70, ...)
	/Users/user/src/go/src/github.com/maliceio/malice/plugins/plugins.go:67 +0xa12
created by github.com/maliceio/malice/commands.ScanSample
	/Users/user/src/go/src/github.com/maliceio/malice/commands/scan.go:110 +0xbcf

 
DEBU[0011] Removing container:                          
ERRO[0011] "Error response from daemon: No container name or ID supplied"
goroutine 57 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0xdef020, 0xc420336050, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420378ca0)
	/Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x7d
github.com/maliceio/malice/malice/errors.CheckError(0xdef020, 0xc420336050, 0x0)
	/Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x62
github.com/maliceio/malice/plugins.Plugin.StartPlugin.func1(0xc420387170, 0xc4203f1d88)
	/Users/user/src/go/src/github.com/maliceio/malice/plugins/plugins.go:60 +0x7d
github.com/maliceio/malice/plugins.Plugin.StartPlugin(0xc42032fcb0, 0x6, 0x1, 0xc42032fe00, 0x2, 0xc42032fd70, 0x6, 0xc42032feb0, 0xd, 0xc420314e70, ...)
	/Users/user/src/go/src/github.com/maliceio/malice/plugins/plugins.go:68 +0xa13
created by github.com/maliceio/malice/commands.ScanSample
	/Users/user/src/go/src/github.com/maliceio/malice/commands/scan.go:110 +0xbcf

 
DEBU[0011] Plugin Container Removed                      env=development name=
```
**Describe the results you expected:**
Don't know, maybe these because they're describing the errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
I also found this:
```
DEBU[0006] Searching for container: nsrl                 env=development
DEBU[0006] name:  nsrl   container.Name:  clamav        
DEBU[0006] MATCH:  false                                
DEBU[0006] name:  nsrl   container.Name:  malice-kibana 
DEBU[0006] MATCH:  false                                
DEBU[0006] name:  nsrl   container.Name:  malice-elastic 
DEBU[0006] MATCH:  false                                
DEBU[0006] Container NOT Found: nsrl                     env=development
DEBU[0006] Searching for image: malice/nsrl:sha1         env=development
DEBU[0006] Image FOUND: malice/virustotal                env=development
DEBU[0006] Image `malice/virustotal` already pulled.     env=development exisits=true
DEBU[0006] Image FOUND: malice/nsrl:sha1                 env=development
DEBU[0006] Image `malice/nsrl:sha1` already pulled.      env=development exisits=true
DEBU[0006] Image FOUND: malice/shadow-server             env=development
DEBU[0006] Image `malice/shadow-server` already pulled.  env=development exisits=true
#### NSRL Database
 - Not Found :grey_question:
DEBU[0008] Plugin Container Started                      env=development name="/nsrl"
DEBU[0008] Removing container: 0e2fff3d061d5c2bd84ec1d54c7f6d4e465a98b9ca5cea6140c3ccdf99bae96a 
DEBU[0008] Plugin Container Removed                      env=development name="/nsrl"
```
And this is just an example, so I see this with `shadow-server`, `floss`, `zoner`, `yara` and others.
What can I do? 

EDIT: I missed a full debug output because it's very long

**Comment by blacktop** [comment]
Is this still an issue with the latest release? https://github.com/maliceio/malice/releases/tag/v0.3.26

This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
