### ISSUE TITLE
ubuntu plugin update --all crash

### ISSUE THREAD

**Issue by blacktop** [maliceio/malice#71]
```bash
➜  ~ malice plugin update --all
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/maliceio/malice/vendor/github.com/Nvveen/Gotty.readTermInfo(0xc0003643c0, 0x1e, 0x0, 0x0, 0x0)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/Nvveen/Gotty/gotty.go:232 +0xcdf
github.com/maliceio/malice/vendor/github.com/Nvveen/Gotty.OpenTermInfo(0xc000022025, 0xe, 0xc000022025, 0xe, 0xc0000561d0)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/Nvveen/Gotty/gotty.go:45 +0x287
github.com/maliceio/malice/vendor/github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0xbbc740, 0xc0002cf500, 0xbbc940, 0xc000090008, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:225 +0x55c
github.com/maliceio/malice/malice/docker/client/image.Pull(0xc000386690, 0xb0f593, 0x7, 0xb0ef8b, 0x6)
        /Users/blacktop/go/src/github.com/maliceio/malice/malice/docker/client/image/image.go:43 +0x181
github.com/maliceio/malice/plugins.UpdateEnabledPlugins(0xc000386690)
        /Users/blacktop/go/src/github.com/maliceio/malice/plugins/plugins.go:248 +0x8f
github.com/maliceio/malice/commands.cmdUpdatePlugin(0x0, 0x0, 0x1, 0x0, 0xc000227680)
        /Users/blacktop/go/src/github.com/maliceio/malice/commands/plugin.go:161 +0x20f
github.com/maliceio/malice/commands.glob..func8(0xc0000a7080, 0x0, 0xc0000a7080)
        /Users/blacktop/go/src/github.com/maliceio/malice/commands/commands.go:138 +0xc1
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0xa10320, 0xb37bc0, 0xc0000a7080, 0xc000227600, 0x0)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0xb0f147, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb12fee, 0xd, 0x0, ...)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:210 +0x990
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000a3520, 0xc0000a6dc0, 0x0, 0x0)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:379 +0x7ef
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.startApp(0xb0effd, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb1ed92, 0x1f, 0x0, ...)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:298 +0x808
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0xb0effd, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb1ed92, 0x1f, 0x0, ...)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:98 +0x1237
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc0000a3380, 0xc000094000, 0x4, 0x4, 0x0, 0x0)
        /Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
        /Users/blacktop/go/src/github.com/maliceio/malice/main.go:88 +0x4b2
```

**Comment by blacktop** [comment]
fixed
