### ISSUE TITLE
Sigterm on watch folder

### ISSUE THREAD

**Issue by Miroqil** [maliceio/malice#91]
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x55f2299df49d]

goroutine 155 [running]:
github.com/maliceio/malice/malice/docker/client/container.parseContainers(0xc4203a4d80, 0xc4204d4e10, 0x24, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/list.go:63 +0x39d
github.com/maliceio/malice/malice/docker/client/container.Exists(0xc4203a4d80, 0xc4204d4e10, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/list.go:40 +0xd5
github.com/maliceio/malice/malice/docker/client/container.checkContainerRequirements(0xc4203a4d80, 0xc4204d4e10, 0x24, 0xc42036f400, 0x17, 0xa)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/utils.go:171 +0x14a
github.com/maliceio/malice/malice/docker/client/container.Start(0xc4203a4d80, 0xc4205ce140, 0x2, 0x2, 0xc4204d4e10, 0x24, 0xc42036f400, 0x17, 0xc4205ce001, 0xc420393410, ...)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/start.go:36 +0xfa
github.com/maliceio/malice/plugins.Plugin.StartPlugin(0xc42036f360, 0x10, 0x1, 0xc420384738, 0x2, 0xc42036f3a0, 0x1a, 0xc42036f400, 0x17, 0xc420371140, ...)
        /go/src/github.com/maliceio/malice/plugins/plugins.go:56 +0x82e
created by github.com/maliceio/malice/commands.cmdScan
        /go/src/github.com/maliceio/malice/commands/scan.go:131 +0xc35
ERRO[0120] "Error: No such container: a8be95c0e0a66e816efe2d7fc9622799a54e7a71c09c848364ef01e446976f0f"
goroutine 155 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0x55f229eaaf60, 0xc4203b0b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x7f
github.com/maliceio/malice/malice/errors.CheckError(0x55f229eaaf60, 0xc4203b0b60, 0x40)
        /go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x4d
github.com/maliceio/malice/malice/docker/client/container.parseContainers(0xc4203a4d80, 0xc4204d4e10, 0x24, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/list.go:61 +0x375
github.com/maliceio/malice/malice/docker/client/container.Exists(0xc4203a4d80, 0xc4204d4e10, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/list.go:40 +0xd5
github.com/maliceio/malice/malice/docker/client/container.checkContainerRequirements(0xc4203a4d80, 0xc4204d4e10, 0x24, 0xc42036f400, 0x17, 0xa)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/utils.go:171 +0x14a
github.com/maliceio/malice/malice/docker/client/container.Start(0xc4203a4d80, 0xc4205ce140, 0x2, 0x2, 0xc4204d4e10, 0x24, 0xc42036f400, 0x17, 0xc4205ce001, 0xc420393410, ...)
        /go/src/github.com/maliceio/malice/malice/docker/client/container/start.go:36 +0xfa
github.com/maliceio/malice/plugins.Plugin.StartPlugin(0xc42036f360, 0x10, 0x1, 0xc420384738, 0x2, 0xc42036f3a0, 0x1a, 0xc42036f400, 0x17, 0xc420371140, ...)
        /go/src/github.com/maliceio/malice/plugins/plugins.go:56 +0x82e
created by github.com/maliceio/malice/commands.cmdScan
        /go/src/github.com/maliceio/malice/commands/scan.go:131 +0xc35
```

**Comment by blacktop** [comment]
Closing due to you not following any issue templates
