### ISSUE TITLE
Some deprecated package import

### ISSUE THREAD

**Issue by kudo28** [maliceio/malice#94]
Hi there, 
I have looked into your project and found that some imported package is no longer available.
For example : 
 - In the file **github.com/maliceio/malice/malice/docker/client/image/** : 
   _"github.com/docker/docker/cli/command/image/build"_  
now become 	
_"github.com/docker/cli/cli/command/image/build"_

Please re-check your entire project to fix that

**Comment by deralexxx** [comment]
yes it would be good to get that fiexed because:
Status: Image is up to date for malice/pdf:latest
[Updating Plugin] ===>  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1577f35]

goroutine 1 [running]:
github.com/maliceio/malice/malice/docker/client/image.Pull(0xc00001e6f0, 0xc0003854a0, 0xd, 0x17306c3, 0x6)
	/Users/blacktop/go/src/github.com/maliceio/malice/malice/docker/client/image/image.go:40 +0x95
github.com/maliceio/malice/plugins.UpdateEnabledPlugins(0xc00001e6f0)
	/Users/blacktop/go/src/github.com/maliceio/malice/plugins/plugins.go:257 +0x2b0
github.com/maliceio/malice/commands.cmdScan(0x7ffeefbffb04, 0x40, 0x0, 0xc000243600, 0x0)
	/Users/blacktop/go/src/github.com/maliceio/malice/commands/scan.go:80 +0xd48
github.com/maliceio/malice/commands.glob..func1(0xc0000d2b00, 0x0, 0xc0000d2b00)
	/Users/blacktop/go/src/github.com/maliceio/malice/commands/commands.go:25 +0x88
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x162b880, 0x1758fc0, 0xc0000d2b00, 0xc000243600, 0x0)
	/Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x172f9f8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1732e04, 0xb, 0x0, ...)
	/Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:210 +0x990
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc0000bd380, 0xc0000b2090, 0x3, 0x3, 0x0, 0x0)
	/Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
	/Users/blacktop/go/src/github.com/maliceio/malice/main.go:88 +0x4b2
